library(RSQLite)
library(tibble)
# setwd("~/zarathu/eCRF-SMCcath")
# Create a connection object with SQLite
conn <- dbConnect(
  RSQLite::SQLite(),
  "data/data.sqlite3"
)

# Create a query to prepare the 'mtcars' table with additional 'uid', 'id',
# & the 4 created/modified columns
create_rct_query <- "CREATE TABLE rct (
  
  -- Initial Add
  pid                             TEXT PRIMARY KEY,
  'Group'                           TEXT,
  Center                          TEXT,
  DM                              TEXT,
  AMI_Type                        TEXT,
  
  -- Demographics --
  Initial                         TEXT,
  Birthday                        DATE,
  Age                             TEXT,
  Sex                             TEXT,
  Agree_Date                      DATE,
  Index_PCI_Date                  DATE,
  Withdrawal                      TEXT,
  SGLT                            TEXT,
  Withdrawal_date                 DATE,
  Withdrawal_reason               TEXT,

  -- Admission --
  Date_adm                        DATE,
  Height                          TEXT,
  Weight                          TEXT,
  BMI                             TEXT,
  BSA_adm                         TEXT,
  SBP_adm                         TEXT,
  DBP_adm                         TEXT,
  HR_adm                          TEXT,
  Diagnosis_adm                   TEXT,
  CCS_adm                         TEXT,
  BC_adm                          TEXT,
  Diagnosis_other_adm             TEXT,
  Diagnosis_comment_adm           TEXT,
  HTN                             TEXT,
  Diabetes_adm                    TEXT,
  Diabetes_detail_adm             TEXT,
  Hld_adm                         TEXT,
  Smoking                         TEXT,
  FHC_adm                         TEXT,
  CRF_adm                         TEXT,
  PCI_adm                         TEXT,
  PCABG_adm                       TEXT,
  PCVA_adm                        TEXT,
  PCHF_adm                        TEXT,
  Pvd_adm                         TEXT,
  PNTB_adm                        TEXT,
  TMT_adm                         TEXT,
  TMT_Date_adm                    DATE,
  TMT_detail_adm                  TEXT,
  MSPECT_adm                      TEXT,
  MSPECT_Date_adm                 DATE,
  MSPECT_detail_adm               TEXT,
  APET_adm                        TEXT,
  APET_Date_adm                   DATE,
  APET_detail_adm                 TEXT,
  CMR_adm                         TEXT,
  CMR_Date_adm                    DATE,
  CMR_detail_adm                  TEXT,
  EEcho_adm                       TEXT,
  EEcho_Date_adm                  DATE,
  EEcho_detail_adm                TEXT,
  Corona_adm                      TEXT,
  Corona_date_adm                 DATE,
  Corona_BB_adm                   TEXT,
  Corona_Nitrate_adm              TEXT,
  EchoCG_adm                      TEXT,
  EchoCG_date_adm                 DATE,
  EchoCG_LVEF_adm                 TEXT,
  EchoCG_LVWMA_adm                TEXT,
  ECG_Rhythm_adm                  TEXT,
  ECG_Rhythm_others_adm           TEXT,
  Lab_Date_adm                    DATE,
  WBC_adm                         TEXT,
  TC_adm                          TEXT,
  Hb_adm                          TEXT,
  TG_adm                          TEXT,
  HDL_adm                         TEXT,
  Platelet_adm                    TEXT,
  LDL_adm                         TEXT,
  BUN_adm                         TEXT,
  Cr_adm                          TEXT,
  FG_adm                          TEXT,
  MDRD_adm                        TEXT,
  HbA1C_adm                       TEXT,
  AST_adm                         TEXT,
  hs_CRP_adm                      TEXT,
  ALT_adm                         TEXT,
  NT_Pro_BNP_adm                  TEXT,
  hCG_adm                         TEXT,
  BCK_adm                         TEXT,
  PCK_adm                         TEXT,
  BCKMB_adm                       TEXT,
  PCKMB_adm                       TEXT,
  BTroT_adm                       TEXT,
  PTroT_adm                       TEXT,
  Aspirin_adm	                		TEXT,
  Clopidogrel_adm	             		TEXT,
  Prasugrel_adm	              		TEXT,
  Ticagrelor_adm	             		TEXT,
  Nicorandil_adm                  TEXT,
  Wafarin_adm                     TEXT,
  NOAC_adm                        TEXT,
  NOAC_name_adm                   TEXT,
  NOAC_dose_adm                   TEXT,
  BB_adm		                   		TEXT,
  BB_name_adm                     TEXT,
  BB_dose_adm                     TEXT,
  DPP4_adm                        TEXT,
  DPP4_name_adm                   TEXT,
  DPP4_dose_adm                   TEXT,
  Metformin_adm                   TEXT,
  Metformin_dose_adm              TEXT,
  Sulf_adm                        TEXT,
  Sulf_name_adm                   TEXT,
  Sulf_dose_adm                   TEXT,
  Thia_adm                        TEXT,
  Thia_name_adm                   TEXT,
  Thia_dose_adm                   TEXT,
  GLP_adm                         TEXT,
  GLP_name_adm                    TEXT,
  GLP_dose_adm                    TEXT,
  Alpha_adm                       TEXT,
  Alpha_name_adm                  TEXT,
  Alpha_dose_adm                  TEXT,
  Statin_adm		                 	TEXT,
  Statin_name_adm                 TEXT,
  Statin_dose_adm                 TEXT,
  ACE_adm	                   			TEXT,
  ACE_name_adm                    TEXT,
  ACE_dose_adm                    TEXT,
  Nitrate_adm	                 		TEXT,
  Calcium_adm	                 		TEXT,
  Calcium_name_adm                TEXT,
  Calcium_dose_adm                TEXT,
  Trimetazidine_adm            		TEXT,
  Insulin_adm                     TEXT,
  Echo_Date_adm                   DATE,
  LVIDs_adm                       TEXT,
  LVEDV_adm                       TEXT,
  LVESV_adm                       TEXT,
  LA_adm                          TEXT,
  LAVI_adm                        TEXT,
  A_adm                           TEXT,
  EA_adm                          TEXT,
  DT_adm                          TEXT,
  ep_adm                          TEXT,
  ap_adm                          TEXT,
  Eep_adm                         TEXT,
  RVSP_adm                        TEXT,
  RAP_adm                         TEXT,
  LVEF_adm                        TEXT,
  Strain_adm                      TEXT,
  CMR_Date_POST_adm               DATE,
  

  -- Angiographics
  Date_ang                        DATE,
  Aspirin_ang                     TEXT,
  Aspirin_loading_ang             TEXT,
  Aspirin_detail_ang              TEXT,
  Clopidogrel_ang                 TEXT,
  Clopidogrel_loading_ang         TEXT,
  Clopidogrel_detail_ang          TEXT,
  Prasugrel_ang                   TEXT,
  Prasugrel_loading_ang           TEXT,
  Prasugrel_detail_ang            TEXT,
  Ticagrelor_ang                  TEXT,
  Ticagrelor_loading_ang          TEXT,
  Ticagrelor_detail_ang           TEXT,
  Procedure_type_ang              TEXT,
  Procedure_dose_ang              TEXT,
  Disease_extent_ang              TEXT,
  Left_main_ang                   TEXT,
  start_hour_ang                  TEXT,
  start_min_ang                   TEXT,
  end_hour_ang                    TEXT,
  end_min_ang                     TEXT,
  time_ang                        TEXT,
  Catheter_diagnostic_ang         TEXT,
  Catheter_guiding_ang            TEXT,
  staged_PCI_ang                  TEXT,
  stagedPCI_count_ang             TEXT,
  Gp_ang                          TEXT,
  Gp_detail_ang                   TEXT,
  Cul_cnt_ang                     TEXT,
  Non_Cul_cnt_ang                 TEXT,
  stagedPCI_1_ang                 DATE,
  stagedPCI_2_ang                 DATE,
  stagedPCI_1_procedure_ang       TEXT,
  stagedPCI_2_procedure_ang       TEXT,
  stagedPCI_1_procedure_dose_ang  TEXT,
  stagedPCI_2_procedure_dose_ang  TEXT,
  start_hour_PCI_1_ang            TEXT,
  start_hour_PCI_2_ang            TEXT,
  start_min_PCI_1_ang             TEXT,
  start_min_PCI_2_ang             TEXT,
  end_hour_PCI_1_ang              TEXT,
  end_hour_PCI_2_ang              TEXT,
  end_min_PCI_1_ang               TEXT,
  end_min_PCI_2_ang               TEXT,
  time_PCI_1_ang                  TEXT,
  time_PCI_2_ang                  TEXT,
  Diagnostic_PCI_1_ang            TEXT,
  Diagnostic_PCI_2_ang            TEXT,
  Guiding_PCI_1_ang               TEXT,
  Guiding_PCI_2_ang               TEXT,

  -- Culprit1

  Vessel_cul1                     TEXT,
  Lesion_cul1                     TEXT,
  Lesion_segment_1_cul1           TEXT,
  Lesion_VeS_1_cul1               TEXT,
  Lesion_segment_2_cul1           TEXT,
  Lesion_VeS_2_cul1               TEXT,
  Lesion_segment_3_cul1           TEXT,
  Lesion_VeS_3_cul1               TEXT,
  Lesion_Type_cul1                TEXT,
  FFR_cul1                        TEXT,
  FFR_pre_cul1                    TEXT,
  FFR_post_cul1                   TEXT,
  Image_cul1                      TEXT,
  Pre_stent_cul1                  TEXT,
  Post_stent_cul1                 TEXT,
  Intervention_cul1               TEXT,
  Intervention_cnt_cul1           TEXT,
  Intervention1_treat_cul1        TEXT,
  Intervention1_segment_cul1      TEXT,
  Intervention1_name_cul1         TEXT,
  Intervention1_diameter_cul1     TEXT,
  Intervention1_length_cul1       TEXT,
  Intervention1_pressure_cul1     TEXT,
  Intervention2_treat_cul1        TEXT,
  Intervention2_segment_cul1      TEXT,
  Intervention2_name_cul1         TEXT,
  Intervention2_diameter_cul1     TEXT,
  Intervention2_length_cul1       TEXT,
  Intervention2_pressure_cul1     TEXT,
  Intervention3_treat_cul1        TEXT,
  Intervention3_segment_cul1      TEXT,
  Intervention3_name_cul1         TEXT,
  Intervention3_diameter_cul1     TEXT,
  Intervention3_length_cul1       TEXT,
  Intervention3_pressure_cul1     TEXT,
  Intervention4_treat_cul1        TEXT,
  Intervention4_segment_cul1      TEXT,
  Intervention4_name_cul1         TEXT,
  Intervention4_diameter_cul1     TEXT,
  Intervention4_length_cul1       TEXT,
  Intervention4_pressure_cul1     TEXT,
  Intervention5_treat_cul1        TEXT,
  Intervention5_segment_cul1      TEXT,
  Intervention5_name_cul1         TEXT,
  Intervention5_diameter_cul1     TEXT,
  Intervention5_length_cul1       TEXT,
  Intervention5_pressure_cul1     TEXT,
  Intervention6_treat_cul1        TEXT,
  Intervention6_segment_cul1      TEXT,
  Intervention6_name_cul1         TEXT,
  Intervention6_diameter_cul1     TEXT,
  Intervention6_length_cul1       TEXT,
  Intervention6_pressure_cul1     TEXT,
  Intervention7_treat_cul1        TEXT,
  Intervention7_segment_cul1      TEXT,
  Intervention7_name_cul1         TEXT,
  Intervention7_diameter_cul1     TEXT,
  Intervention7_length_cul1       TEXT,
  Intervention7_pressure_cul1     TEXT,
  Intervention8_treat_cul1        TEXT,
  Intervention8_segment_cul1      TEXT,
  Intervention8_name_cul1         TEXT,
  Intervention8_diameter_cul1     TEXT,
  Intervention8_length_cul1       TEXT,
  Intervention8_pressure_cul1     TEXT,
  Intervention9_treat_cul1        TEXT,
  Intervention9_segment_cul1      TEXT,
  Intervention9_name_cul1         TEXT,
  Intervention9_diameter_cul1     TEXT,
  Intervention9_length_cul1       TEXT,
  Intervention9_pressure_cul1     TEXT,
  Intervention10_treat_cul1       TEXT,
  Intervention10_segment_cul1     TEXT,
  Intervention10_name_cul1        TEXT,
  Intervention10_diameter_cul1    TEXT,
  Intervention10_length_cul1      TEXT,
  Intervention10_pressure_cul1    TEXT,
  Intervention_ab_cul1            TEXT,
  Intervention_ab_diameter_cul1   TEXT,
  Intervention_ab_length_cul1     TEXT,
  Intervention_ab_pressure_cul1   TEXT,
  Intervention_Rota_cul1          TEXT,
  Intervention_cd_cul1            TEXT,
  Intervention_cl_cul1            TEXT,
  Intervention_SRS_cul1           TEXT,
  Intervention_NR_cul1            TEXT,
  Intervention_D_cul1             TEXT,
  Intervention_AC_cul1            TEXT,
  Intervention_O_cul1             TEXT,
  Intervention_O_detail_cul1      TEXT,
  -- Intervention_P_cul1             TEXT,
  Intervention_CPS_cul1           TEXT,
  Intervention_CPS_detail_cul1    TEXT,
  Trombosuction_cul1              TEXT,
  Perforation_cul1                TEXT,
  
  -- Culprit2
  
  Vessel_cul2                     TEXT,
  Lesion_cul2                     TEXT,
  Lesion_segment_1_cul2           TEXT,
  Lesion_VeS_1_cul2               TEXT,
  Lesion_segment_2_cul2           TEXT,
  Lesion_VeS_2_cul2               TEXT,
  Lesion_segment_3_cul2           TEXT,
  Lesion_VeS_3_cul2               TEXT,
  Lesion_Type_cul2                TEXT,
  FFR_cul2                        TEXT,
  FFR_pre_cul2                    TEXT,
  FFR_post_cul2                   TEXT,
  Image_cul2                      TEXT,
  Pre_stent_cul2                  TEXT,
  Post_stent_cul2                 TEXT,
  Intervention_cul2               TEXT,
  Intervention_cnt_cul2           TEXT,
  Intervention1_treat_cul2        TEXT,
  Intervention1_segment_cul2      TEXT,
  Intervention1_name_cul2         TEXT,
  Intervention1_diameter_cul2     TEXT,
  Intervention1_length_cul2       TEXT,
  Intervention1_pressure_cul2     TEXT,
  Intervention2_treat_cul2        TEXT,
  Intervention2_segment_cul2      TEXT,
  Intervention2_name_cul2         TEXT,
  Intervention2_diameter_cul2     TEXT,
  Intervention2_length_cul2       TEXT,
  Intervention2_pressure_cul2     TEXT,
  Intervention3_treat_cul2        TEXT,
  Intervention3_segment_cul2      TEXT,
  Intervention3_name_cul2         TEXT,
  Intervention3_diameter_cul2     TEXT,
  Intervention3_length_cul2       TEXT,
  Intervention3_pressure_cul2     TEXT,
  Intervention4_treat_cul2        TEXT,
  Intervention4_segment_cul2      TEXT,
  Intervention4_name_cul2         TEXT,
  Intervention4_diameter_cul2     TEXT,
  Intervention4_length_cul2       TEXT,
  Intervention4_pressure_cul2     TEXT,
  Intervention5_treat_cul2        TEXT,
  Intervention5_segment_cul2      TEXT,
  Intervention5_name_cul2         TEXT,
  Intervention5_diameter_cul2     TEXT,
  Intervention5_length_cul2       TEXT,
  Intervention5_pressure_cul2     TEXT,
  Intervention6_treat_cul2        TEXT,
  Intervention6_segment_cul2      TEXT,
  Intervention6_name_cul2         TEXT,
  Intervention6_diameter_cul2     TEXT,
  Intervention6_length_cul2       TEXT,
  Intervention6_pressure_cul2     TEXT,
  Intervention7_treat_cul2        TEXT,
  Intervention7_segment_cul2      TEXT,
  Intervention7_name_cul2         TEXT,
  Intervention7_diameter_cul2     TEXT,
  Intervention7_length_cul2       TEXT,
  Intervention7_pressure_cul2     TEXT,
  Intervention8_treat_cul2        TEXT,
  Intervention8_segment_cul2      TEXT,
  Intervention8_name_cul2         TEXT,
  Intervention8_diameter_cul2     TEXT,
  Intervention8_length_cul2       TEXT,
  Intervention8_pressure_cul2     TEXT,
  Intervention9_treat_cul2        TEXT,
  Intervention9_segment_cul2      TEXT,
  Intervention9_name_cul2         TEXT,
  Intervention9_diameter_cul2     TEXT,
  Intervention9_length_cul2       TEXT,
  Intervention9_pressure_cul2     TEXT,
  Intervention10_treat_cul2       TEXT,
  Intervention10_segment_cul2     TEXT,
  Intervention10_name_cul2        TEXT,
  Intervention10_diameter_cul2    TEXT,
  Intervention10_length_cul2      TEXT,
  Intervention10_pressure_cul2    TEXT,
  Intervention_ab_cul2            TEXT,
  Intervention_ab_diameter_cul2   TEXT,
  Intervention_ab_length_cul2     TEXT,
  Intervention_ab_pressure_cul2   TEXT,
  Intervention_Rota_cul2          TEXT,
  Intervention_cd_cul2            TEXT,
  Intervention_cl_cul2            TEXT,
  Intervention_SRS_cul2           TEXT,
  Intervention_NR_cul2            TEXT,
  Intervention_D_cul2             TEXT,
  Intervention_AC_cul2            TEXT,
  Intervention_O_cul2             TEXT,
  Intervention_O_detail_cul2      TEXT,
  -- Intervention_P_cul2             TEXT,
  Intervention_CPS_cul2           TEXT,
  Intervention_CPS_detail_cul2    TEXT,
  Trombosuction_cul2              TEXT,
  Perforation_cul2                TEXT,

  
  -- Non-Culprit1
  
  Vessel_culn1                     TEXT,
  Lesion_culn1                     TEXT,
  Lesion_segment_1_culn1           TEXT,
  Lesion_VeS_1_culn1               TEXT,
  Lesion_segment_2_culn1           TEXT,
  Lesion_VeS_2_culn1               TEXT,
  Lesion_segment_3_culn1           TEXT,
  Lesion_VeS_3_culn1               TEXT,
  Lesion_Type_culn1                TEXT,
  FFR_culn1                        TEXT,
  FFR_pre_culn1                    TEXT,
  FFR_post_culn1                   TEXT,
  Image_culn1                      TEXT,
  Pre_stent_culn1                  TEXT,
  Post_stent_culn1                 TEXT,
  Intervention_culn1               TEXT,
  Intervention_cnt_culn1           TEXT,
  Intervention1_treat_culn1        TEXT,
  Intervention1_segment_culn1      TEXT,
  Intervention1_name_culn1         TEXT,
  Intervention1_diameter_culn1     TEXT,
  Intervention1_length_culn1       TEXT,
  Intervention1_pressure_culn1     TEXT,
  Intervention2_treat_culn1        TEXT,
  Intervention2_segment_culn1      TEXT,
  Intervention2_name_culn1         TEXT,
  Intervention2_diameter_culn1     TEXT,
  Intervention2_length_culn1       TEXT,
  Intervention2_pressure_culn1     TEXT,
  Intervention3_treat_culn1        TEXT,
  Intervention3_segment_culn1      TEXT,
  Intervention3_name_culn1         TEXT,
  Intervention3_diameter_culn1     TEXT,
  Intervention3_length_culn1       TEXT,
  Intervention3_pressure_culn1     TEXT,
  Intervention4_treat_culn1        TEXT,
  Intervention4_segment_culn1      TEXT,
  Intervention4_name_culn1         TEXT,
  Intervention4_diameter_culn1     TEXT,
  Intervention4_length_culn1       TEXT,
  Intervention4_pressure_culn1     TEXT,
  Intervention5_treat_culn1        TEXT,
  Intervention5_segment_culn1      TEXT,
  Intervention5_name_culn1         TEXT,
  Intervention5_diameter_culn1     TEXT,
  Intervention5_length_culn1       TEXT,
  Intervention5_pressure_culn1     TEXT,
  Intervention6_treat_culn1        TEXT,
  Intervention6_segment_culn1      TEXT,
  Intervention6_name_culn1         TEXT,
  Intervention6_diameter_culn1     TEXT,
  Intervention6_length_culn1       TEXT,
  Intervention6_pressure_culn1     TEXT,
  Intervention7_treat_culn1        TEXT,
  Intervention7_segment_culn1      TEXT,
  Intervention7_name_culn1         TEXT,
  Intervention7_diameter_culn1     TEXT,
  Intervention7_length_culn1       TEXT,
  Intervention7_pressure_culn1     TEXT,
  Intervention8_treat_culn1        TEXT,
  Intervention8_segment_culn1      TEXT,
  Intervention8_name_culn1         TEXT,
  Intervention8_diameter_culn1     TEXT,
  Intervention8_length_culn1       TEXT,
  Intervention8_pressure_culn1     TEXT,
  Intervention9_treat_culn1        TEXT,
  Intervention9_segment_culn1      TEXT,
  Intervention9_name_culn1         TEXT,
  Intervention9_diameter_culn1     TEXT,
  Intervention9_length_culn1       TEXT,
  Intervention9_pressure_culn1     TEXT,
  Intervention10_treat_culn1       TEXT,
  Intervention10_segment_culn1     TEXT,
  Intervention10_name_culn1        TEXT,
  Intervention10_diameter_culn1    TEXT,
  Intervention10_length_culn1      TEXT,
  Intervention10_pressure_culn1    TEXT,
  Intervention_ab_culn1            TEXT,
  Intervention_ab_diameter_culn1   TEXT,
  Intervention_ab_length_culn1     TEXT,
  Intervention_ab_pressure_culn1   TEXT,
  Intervention_Rota_culn1          TEXT,
  Intervention_cd_culn1            TEXT,
  Intervention_cl_culn1            TEXT,
  Intervention_SRS_culn1           TEXT,
  Intervention_NR_culn1            TEXT,
  Intervention_D_culn1             TEXT,
  Intervention_AC_culn1            TEXT,
  Intervention_O_culn1             TEXT,
  Intervention_O_detail_culn1      TEXT,
  -- Intervention_P_culn1             TEXT,
  Intervention_CPS_culn1           TEXT,
  Intervention_CPS_detail_culn1    TEXT,
  Trombosuction_culn1              TEXT,
  Perforation_culn1                TEXT,


  -- Non-Culprit2
  
  Vessel_culn2                     TEXT,
  Lesion_culn2                     TEXT,
  Lesion_segment_1_culn2           TEXT,
  Lesion_VeS_1_culn2               TEXT,
  Lesion_segment_2_culn2           TEXT,
  Lesion_VeS_2_culn2               TEXT,
  Lesion_segment_3_culn2           TEXT,
  Lesion_VeS_3_culn2               TEXT,
  Lesion_Type_culn2                TEXT,
  FFR_culn2                        TEXT,
  FFR_pre_culn2                    TEXT,
  FFR_post_culn2                   TEXT,
  Image_culn2                      TEXT,
  Pre_stent_culn2                  TEXT,
  Post_stent_culn2                 TEXT,
  Intervention_culn2               TEXT,
  Intervention_cnt_culn2           TEXT,
  Intervention1_treat_culn2        TEXT,
  Intervention1_segment_culn2      TEXT,
  Intervention1_name_culn2         TEXT,
  Intervention1_diameter_culn2     TEXT,
  Intervention1_length_culn2       TEXT,
  Intervention1_pressure_culn2     TEXT,
  Intervention2_treat_culn2        TEXT,
  Intervention2_segment_culn2      TEXT,
  Intervention2_name_culn2         TEXT,
  Intervention2_diameter_culn2     TEXT,
  Intervention2_length_culn2       TEXT,
  Intervention2_pressure_culn2     TEXT,
  Intervention3_treat_culn2        TEXT,
  Intervention3_segment_culn2      TEXT,
  Intervention3_name_culn2         TEXT,
  Intervention3_diameter_culn2     TEXT,
  Intervention3_length_culn2       TEXT,
  Intervention3_pressure_culn2     TEXT,
  Intervention4_treat_culn2        TEXT,
  Intervention4_segment_culn2      TEXT,
  Intervention4_name_culn2         TEXT,
  Intervention4_diameter_culn2     TEXT,
  Intervention4_length_culn2       TEXT,
  Intervention4_pressure_culn2     TEXT,
  Intervention5_treat_culn2        TEXT,
  Intervention5_segment_culn2      TEXT,
  Intervention5_name_culn2         TEXT,
  Intervention5_diameter_culn2     TEXT,
  Intervention5_length_culn2       TEXT,
  Intervention5_pressure_culn2     TEXT,
  Intervention6_treat_culn2        TEXT,
  Intervention6_segment_culn2      TEXT,
  Intervention6_name_culn2         TEXT,
  Intervention6_diameter_culn2     TEXT,
  Intervention6_length_culn2       TEXT,
  Intervention6_pressure_culn2     TEXT,
  Intervention7_treat_culn2        TEXT,
  Intervention7_segment_culn2      TEXT,
  Intervention7_name_culn2         TEXT,
  Intervention7_diameter_culn2     TEXT,
  Intervention7_length_culn2       TEXT,
  Intervention7_pressure_culn2     TEXT,
  Intervention8_treat_culn2        TEXT,
  Intervention8_segment_culn2      TEXT,
  Intervention8_name_culn2         TEXT,
  Intervention8_diameter_culn2     TEXT,
  Intervention8_length_culn2       TEXT,
  Intervention8_pressure_culn2     TEXT,
  Intervention9_treat_culn2        TEXT,
  Intervention9_segment_culn2      TEXT,
  Intervention9_name_culn2         TEXT,
  Intervention9_diameter_culn2     TEXT,
  Intervention9_length_culn2       TEXT,
  Intervention9_pressure_culn2     TEXT,
  Intervention10_treat_culn2       TEXT,
  Intervention10_segment_culn2     TEXT,
  Intervention10_name_culn2        TEXT,
  Intervention10_diameter_culn2    TEXT,
  Intervention10_length_culn2      TEXT,
  Intervention10_pressure_culn2    TEXT,
  Intervention_ab_culn2            TEXT,
  Intervention_ab_diameter_culn2   TEXT,
  Intervention_ab_length_culn2     TEXT,
  Intervention_ab_pressure_culn2   TEXT,
  Intervention_Rota_culn2          TEXT,
  Intervention_cd_culn2            TEXT,
  Intervention_cl_culn2            TEXT,
  Intervention_SRS_culn2           TEXT,
  Intervention_NR_culn2            TEXT,
  Intervention_D_culn2             TEXT,
  Intervention_AC_culn2            TEXT,
  Intervention_O_culn2             TEXT,
  Intervention_O_detail_culn2      TEXT,
  -- Intervention_P_culn2             TEXT,
  Intervention_CPS_culn2           TEXT,
  Intervention_CPS_detail_culn2    TEXT,
  Trombosuction_culn2              TEXT,
  Perforation_culn2                TEXT,

  
  -- Non-Culprit3

  Vessel_culn3                     TEXT,
  Lesion_culn3                     TEXT,
  Lesion_segment_1_culn3           TEXT,
  Lesion_VeS_1_culn3               TEXT,
  Lesion_segment_2_culn3           TEXT,
  Lesion_VeS_2_culn3               TEXT,
  Lesion_segment_3_culn3           TEXT,
  Lesion_VeS_3_culn3               TEXT,
  Lesion_Type_culn3                TEXT,
  FFR_culn3                        TEXT,
  FFR_pre_culn3                    TEXT,
  FFR_post_culn3                   TEXT,
  Image_culn3                      TEXT,
  Pre_stent_culn3                  TEXT,
  Post_stent_culn3                 TEXT,
  Intervention_culn3               TEXT,
  Intervention_cnt_culn3           TEXT,
  Intervention1_treat_culn3        TEXT,
  Intervention1_segment_culn3      TEXT,
  Intervention1_name_culn3         TEXT,
  Intervention1_diameter_culn3     TEXT,
  Intervention1_length_culn3       TEXT,
  Intervention1_pressure_culn3     TEXT,
  Intervention2_treat_culn3        TEXT,
  Intervention2_segment_culn3      TEXT,
  Intervention2_name_culn3         TEXT,
  Intervention2_diameter_culn3     TEXT,
  Intervention2_length_culn3       TEXT,
  Intervention2_pressure_culn3     TEXT,
  Intervention3_treat_culn3        TEXT,
  Intervention3_segment_culn3      TEXT,
  Intervention3_name_culn3         TEXT,
  Intervention3_diameter_culn3     TEXT,
  Intervention3_length_culn3       TEXT,
  Intervention3_pressure_culn3     TEXT,
  Intervention4_treat_culn3        TEXT,
  Intervention4_segment_culn3      TEXT,
  Intervention4_name_culn3         TEXT,
  Intervention4_diameter_culn3     TEXT,
  Intervention4_length_culn3       TEXT,
  Intervention4_pressure_culn3     TEXT,
  Intervention5_treat_culn3        TEXT,
  Intervention5_segment_culn3      TEXT,
  Intervention5_name_culn3         TEXT,
  Intervention5_diameter_culn3     TEXT,
  Intervention5_length_culn3       TEXT,
  Intervention5_pressure_culn3     TEXT,
  Intervention6_treat_culn3        TEXT,
  Intervention6_segment_culn3      TEXT,
  Intervention6_name_culn3         TEXT,
  Intervention6_diameter_culn3     TEXT,
  Intervention6_length_culn3       TEXT,
  Intervention6_pressure_culn3     TEXT,
  Intervention7_treat_culn3        TEXT,
  Intervention7_segment_culn3      TEXT,
  Intervention7_name_culn3         TEXT,
  Intervention7_diameter_culn3     TEXT,
  Intervention7_length_culn3       TEXT,
  Intervention7_pressure_culn3     TEXT,
  Intervention8_treat_culn3        TEXT,
  Intervention8_segment_culn3      TEXT,
  Intervention8_name_culn3         TEXT,
  Intervention8_diameter_culn3     TEXT,
  Intervention8_length_culn3       TEXT,
  Intervention8_pressure_culn3     TEXT,
  Intervention9_treat_culn3        TEXT,
  Intervention9_segment_culn3      TEXT,
  Intervention9_name_culn3         TEXT,
  Intervention9_diameter_culn3     TEXT,
  Intervention9_length_culn3       TEXT,
  Intervention9_pressure_culn3     TEXT,
  Intervention10_treat_culn3       TEXT,
  Intervention10_segment_culn3     TEXT,
  Intervention10_name_culn3        TEXT,
  Intervention10_diameter_culn3    TEXT,
  Intervention10_length_culn3      TEXT,
  Intervention10_pressure_culn3    TEXT,
  Intervention_ab_culn3            TEXT,
  Intervention_ab_diameter_culn3   TEXT,
  Intervention_ab_length_culn3     TEXT,
  Intervention_ab_pressure_culn3   TEXT,
  Intervention_Rota_culn3          TEXT,
  Intervention_cd_culn3            TEXT,
  Intervention_cl_culn3            TEXT,
  Intervention_SRS_culn3           TEXT,
  Intervention_NR_culn3            TEXT,
  Intervention_D_culn3             TEXT,
  Intervention_AC_culn3            TEXT,
  Intervention_O_culn3             TEXT,
  Intervention_O_detail_culn3      TEXT,
  -- Intervention_P_culn3             TEXT,
  Intervention_CPS_culn3           TEXT,
  Intervention_CPS_detail_culn3    TEXT,
  Trombosuction_culn3              TEXT,
  Perforation_culn3                TEXT,

  -- Non-Culprit4

  Vessel_culn4                     TEXT,
  Lesion_culn4                     TEXT,
  Lesion_segment_1_culn4           TEXT,
  Lesion_VeS_1_culn4               TEXT,
  Lesion_segment_2_culn4           TEXT,
  Lesion_VeS_2_culn4               TEXT,
  Lesion_segment_3_culn4           TEXT,
  Lesion_VeS_3_culn4               TEXT,
  Lesion_Type_culn4                TEXT,
  FFR_culn4                        TEXT,
  FFR_pre_culn4                    TEXT,
  FFR_post_culn4                   TEXT,
  Image_culn4                      TEXT,
  Pre_stent_culn4                  TEXT,
  Post_stent_culn4                 TEXT,
  Intervention_culn4               TEXT,
  Intervention_cnt_culn4           TEXT,
  Intervention1_treat_culn4        TEXT,
  Intervention1_segment_culn4      TEXT,
  Intervention1_name_culn4         TEXT,
  Intervention1_diameter_culn4     TEXT,
  Intervention1_length_culn4       TEXT,
  Intervention1_pressure_culn4     TEXT,
  Intervention2_treat_culn4        TEXT,
  Intervention2_segment_culn4      TEXT,
  Intervention2_name_culn4         TEXT,
  Intervention2_diameter_culn4     TEXT,
  Intervention2_length_culn4       TEXT,
  Intervention2_pressure_culn4     TEXT,
  Intervention3_treat_culn4        TEXT,
  Intervention3_segment_culn4      TEXT,
  Intervention3_name_culn4         TEXT,
  Intervention3_diameter_culn4     TEXT,
  Intervention3_length_culn4       TEXT,
  Intervention3_pressure_culn4     TEXT,
  Intervention4_treat_culn4        TEXT,
  Intervention4_segment_culn4      TEXT,
  Intervention4_name_culn4         TEXT,
  Intervention4_diameter_culn4     TEXT,
  Intervention4_length_culn4       TEXT,
  Intervention4_pressure_culn4     TEXT,
  Intervention5_treat_culn4        TEXT,
  Intervention5_segment_culn4      TEXT,
  Intervention5_name_culn4         TEXT,
  Intervention5_diameter_culn4     TEXT,
  Intervention5_length_culn4       TEXT,
  Intervention5_pressure_culn4     TEXT,
  Intervention6_treat_culn4        TEXT,
  Intervention6_segment_culn4      TEXT,
  Intervention6_name_culn4         TEXT,
  Intervention6_diameter_culn4     TEXT,
  Intervention6_length_culn4       TEXT,
  Intervention6_pressure_culn4     TEXT,
  Intervention7_treat_culn4        TEXT,
  Intervention7_segment_culn4      TEXT,
  Intervention7_name_culn4         TEXT,
  Intervention7_diameter_culn4     TEXT,
  Intervention7_length_culn4       TEXT,
  Intervention7_pressure_culn4     TEXT,
  Intervention8_treat_culn4        TEXT,
  Intervention8_segment_culn4      TEXT,
  Intervention8_name_culn4         TEXT,
  Intervention8_diameter_culn4     TEXT,
  Intervention8_length_culn4       TEXT,
  Intervention8_pressure_culn4     TEXT,
  Intervention9_treat_culn4        TEXT,
  Intervention9_segment_culn4      TEXT,
  Intervention9_name_culn4         TEXT,
  Intervention9_diameter_culn4     TEXT,
  Intervention9_length_culn4       TEXT,
  Intervention9_pressure_culn4     TEXT,
  Intervention10_treat_culn4       TEXT,
  Intervention10_segment_culn4     TEXT,
  Intervention10_name_culn4        TEXT,
  Intervention10_diameter_culn4    TEXT,
  Intervention10_length_culn4      TEXT,
  Intervention10_pressure_culn4    TEXT,
  Intervention_ab_culn4            TEXT,
  Intervention_ab_diameter_culn4   TEXT,
  Intervention_ab_length_culn4     TEXT,
  Intervention_ab_pressure_culn4   TEXT,
  Intervention_Rota_culn4          TEXT,
  Intervention_cd_culn4            TEXT,
  Intervention_cl_culn4            TEXT,
  Intervention_SRS_culn4           TEXT,
  Intervention_NR_culn4            TEXT,
  Intervention_D_culn4             TEXT,
  Intervention_AC_culn4            TEXT,
  Intervention_O_culn4             TEXT,
  Intervention_O_detail_culn4      TEXT,
  -- Intervention_P_culn4             TEXT,
  Intervention_CPS_culn4           TEXT,
  Intervention_CPS_detail_culn4    TEXT,
  Trombosuction_culn4              TEXT,
  Perforation_culn4                TEXT,

  -- Outcomes

  Discharge_out                   DATE,
  General_out                     TEXT,
  General_detail_out              TEXT,
  General_detail_others_out       TEXT,
  
  Aspirin_out	                		TEXT,
  Clopidogrel_out	             		TEXT,
  Prasugrel_out	              		TEXT,
  Ticagrelor_out	             		TEXT,
  Nicorandil_out                  TEXT,
  Wafarin_out                     TEXT,
  NOAC_out                        TEXT,
  NOAC_name_out                   TEXT,
  NOAC_dose_out                   TEXT,
  BB_out		                   		TEXT,
  BB_name_out                     TEXT,
  BB_dose_out                     TEXT,
  DPP4_out                        TEXT,
  DPP4_name_out                   TEXT,
  DPP4_dose_out                   TEXT,
  Metformin_out                   TEXT,
  Metformin_dose_out              TEXT,
  Sulf_out                        TEXT,
  Sulf_name_out                   TEXT,
  Sulf_dose_out                   TEXT,
  Thia_out                        TEXT,
  Thia_name_out                   TEXT,
  Thia_dose_out                   TEXT,
  GLP_out                         TEXT,
  GLP_name_out                    TEXT,
  GLP_dose_out                    TEXT,
  Alpha_out                       TEXT,
  Alpha_name_out                  TEXT,
  Alpha_dose_out                  TEXT,
  Statin_out		                 	TEXT,
  Statin_name_out                 TEXT,
  Statin_dose_out                 TEXT,
  ACE_out	                   			TEXT,
  ACE_name_out                    TEXT,
  ACE_dose_out                    TEXT,
  Nitrate_out	                 		TEXT,
  Calcium_out	                 		TEXT,
  Calcium_name_out                TEXT,
  Calcium_dose_out                TEXT,
  Trimetazidine_out            		TEXT,
  Insulin_out                     TEXT,
  Events_out                      TEXT,
  Events_detail_out               TEXT,
  Death_date_out                  DATE,
  Death_cause_out                 TEXT,
  MI_date_out                     DATE,
  MI_Segment_out                  TEXT,
  MI_Type_out                     TEXT,
  MI_Pre_out                      TEXT,
  MI_ST_out                       TEXT,
  MI_TL_out                       TEXT,
  MI_TV_out                       TEXT,
  MI_Treat_out                    TEXT,
  MI_After_out                    TEXT,
  
  RV_date_out                     DATE,
  RV_Segment_out                  TEXT,
  RV_CD_out                       TEXT,
  RV_ID_out                       TEXT,
  RV_Treat_out                    TEXT,
  RV_TL_out                       TEXT,
  RV_TV_out                       TEXT,
  RV_AVP_out                      TEXT,
  
  ST_date_out                     DATE,
  ST_Segment_out                  TEXT,
  ST_Type_out                     TEXT,
  ST_ARC_out                      TEXT,
  ST_Clinical_out                 TEXT,
  ST_Clinical_other_out           TEXT,
  
  CVA_date_out                    DATE,
  CVA_Type_out                    TEXT,
  CVA_VIS_out                     TEXT,
  
  Bleed_count_out                 TEXT,
  Bleed1_date_out                 DATE,
  BARC1_Type_out                  TEXT,
  BARC1_ST_out                    TEXT,
  BARC1_HT_out                    TEXT,
  BARC1_Origin_out                TEXT,
  BARC1_AT_out                    TEXT,
  Bleed2_date_out                 DATE,
  BARC2_Type_out                  TEXT,
  BARC2_ST_out                    TEXT,
  BARC2_HT_out                    TEXT,
  BARC2_Origin_out                TEXT,
  BARC2_AT_out                    TEXT,
  
  Comment_out                     TEXT,


  -- Event --
  -- Last_FU_Date                    DATE,
  -- Death                           TEXT,
  -- Death_Date                      DATE,
  -- MI                              TEXT,
  -- MI_Date                         DATE,
  -- TVMI                            TEXT,
  -- TVMI_Date                       DATE,
  -- TLR                             TEXT,
  -- TLR_Date                        DATE,
  -- TVR                             TEXT,
  -- TVR_Date                        DATE,
  -- Readmission_Total               TEXT,
  -- Readmission_Total_Date          DATE,
  -- TLF                             TEXT,
  -- TLF_Date                        DATE,

  -- Lab --
  -- Lab_Date                        DATE,
  -- WBC                             TEXT,
  -- Hb                              TEXT,
  -- Plt                             TEXT,
  -- Cholesterol                     TEXT,
  -- TG                              TEXT,
  -- LDL                             TEXT,
  -- HDL                             TEXT,
  -- BUN                             TEXT,
  -- Creatinine                      TEXT,
  -- eCFR                            TEXT,
  -- Bilirubin                       TEXT,
  -- AST                             TEXT,
  -- ALT                             TEXT,
  -- hsCRP                           TEXT,
  -- HbA1c                           TEXT,
  -- Pre_CK_MB                       TEXT,
  -- Pre_cTnT                        TEXT,
  -- Post_Peak_CK_MB                 TEXT,
  -- Post_Peak_cTnT                  TEXT,
  -- NT_proBNP_Baseline              TEXT,
  -- Lactic_Acid_Pre                 TEXT,
  -- Lactic_Acid_Peak                TEXT,

  -- M1 --
  FU_M1                           TEXT,
  Visit_Date_M1                   DATE,
  Visit_M1                        TEXT,
  Reason_M1                       TEXT,
  Other_M1                        TEXT,
  LastFU_M1                       DATE,
  SBP_M1                          TEXT,
  DBP_M1                          TEXT,
  HRT_M1                          TEXT,
  Event_M1                        TEXT,
  Cardiac_Status_M1		            TEXT,
  CCS_M1				                  TEXT,
  Other_Cardiac_Status_M1		      TEXT,
  -- Readmission_M1		            	TEXT,
  -- Readmission_Date_M1             DATE,
  -- Readmission_reason_M1       		TEXT,
  -- Readmission_reason_text_M1    	TEXT,
  ECG_Rhythm_M1	              		TEXT,
  ECG_Rhythm_Other_M1	          	TEXT,
  Stress_ECG_M1		              	TEXT,
  Stress_ECG_Date_M1	          	DATE,
  Stress_ECG_Detail_M1	        	TEXT,
  
  Lab_Date_M1		                	DATE,
  WBC_M1                         TEXT,
  TC_M1                          TEXT,
  Hb_M1                          TEXT,
  TG_M1                          TEXT,
  HDL_M1                         TEXT,
  Platelet_M1                    TEXT,
  LDL_M1                         TEXT,
  BUN_M1                         TEXT,
  Cr_M1                          TEXT,
  FG_M1                          TEXT,
  MDRD_M1                        TEXT,
  HbA1C_M1                       TEXT,
  AST_M1                         TEXT,
  hs_CRP_M1                      TEXT,
  ALT_M1                         TEXT,
  NT_Pro_BNP_M1                  TEXT,

  Aspirin_M1	                	 TEXT,
  Clopidogrel_M1	             	 TEXT,
  Prasugrel_M1	              	 TEXT,
  Ticagrelor_M1	             		 TEXT,
  Nicorandil_M1                  TEXT,
  Wafarin_M1                     TEXT,
  NOAC_M1                        TEXT,
  NOAC_name_M1                   TEXT,
  NOAC_dose_M1                   TEXT,
  BB_M1		                   		 TEXT,
  BB_name_M1                     TEXT,
  BB_dose_M1                     TEXT,
  DPP4_M1                        TEXT,
  DPP4_name_M1                   TEXT,
  DPP4_dose_M1                   TEXT,
  Metformin_M1                   TEXT,
  Metformin_dose_M1              TEXT,
  Sulf_M1                        TEXT,
  Sulf_name_M1                   TEXT,
  Sulf_dose_M1                   TEXT,
  Thia_M1                        TEXT,
  Thia_name_M1                   TEXT,
  Thia_dose_M1                   TEXT,
  GLP_M1                         TEXT,
  GLP_name_M1                    TEXT,
  GLP_dose_M1                    TEXT,
  Alpha_M1                       TEXT,
  Alpha_name_M1                  TEXT,
  Alpha_dose_M1                  TEXT,
  Statin_M1		                 	 TEXT,
  Statin_name_M1                 TEXT,
  Statin_dose_M1                 TEXT,
  ACE_M1	                   		 TEXT,
  ACE_name_M1                    TEXT,
  ACE_dose_M1                    TEXT,
  Nitrate_M1	                 	 TEXT,
  Calcium_M1	                 	 TEXT,
  Calcium_name_M1                TEXT,
  Calcium_dose_M1                TEXT,
  Trimetazidine_M1            	 TEXT,
  Insulin_M1                     TEXT,
 
  Event_Details_M1	             	TEXT,
  Death_date_M1		              	DATE,
  Death_reason_M1	              	TEXT,
  MI_date_M1		                	DATE,
  MI_Segment_M1		              	TEXT,
  MI_Type_M1		                	TEXT,
  MI_Stent_M1	                		TEXT,
  MI_Lesion_M1              			TEXT,
  MI_Vessel_M1	              		TEXT,
  MI_Treatment_M1	              	TEXT,
  MI_After_M1		                	TEXT,
  Rev_date_M1		                	DATE,
  Rev_Segment_M1	             		TEXT,
  Rev_Treatment_M1	             	TEXT,
  Rev_Lesion_M1	              		TEXT,
  Rev_Vessel_M1		              	TEXT,
  Rev_PCI_M1		                	TEXT,
  Stent_date_M1	              		DATE,
  Stent_Segment_M1            		TEXT,
  Stent_Type_M1		              	TEXT,
  Stent_arc_M1	              		TEXT,
  Clinical_feature_M1	          	TEXT,
  Clinical_feature_other_M1     	TEXT,
  CVA_date_M1		                	DATE,
  CVA_Type_M1	                		TEXT,
  
  Bleed_count_M1                 TEXT,
  Bleed1_date_M1                 DATE,
  BARC1_Type_M1                  TEXT,
  BARC1_ST_M1                    TEXT,
  BARC1_HT_M1                    TEXT,
  BARC1_Origin_M1                TEXT,
  BARC1_AT_M1                    TEXT,
  Bleed2_date_M1                 DATE,
  BARC2_Type_M1                  TEXT,
  BARC2_ST_M1                    TEXT,
  BARC2_HT_M1                    TEXT,
  BARC2_Origin_M1                TEXT,
  BARC2_AT_M1                    TEXT,
  
  Readmission_Date_M1             DATE,
  Readmission_Type_M1             TEXT,
  Readmission_Other_M1            TEXT,
  
  Imaging_M1	                		TEXT,
  Comment_M1	                		TEXT,

 
 -- M3 --
  FU_M3                           TEXT,
  Visit_Date_M3                   DATE,
  Visit_M3                        TEXT,
  Reason_M3                       TEXT,
  Other_M3                        TEXT,
  LastFU_M3                       DATE,
  SBP_M3                          TEXT,
  DBP_M3                          TEXT,
  HRT_M3                          TEXT,
  Event_M3                        TEXT,
  Cardiac_Status_M3		            TEXT,
  CCS_M3				                  TEXT,
  Other_Cardiac_Status_M3		      TEXT,
  -- Readmission_M3		            	TEXT,
  -- Readmission_Date_M3             DATE,
  -- Readmission_reason_M3       		TEXT,
  -- Readmission_reason_text_M3    	TEXT,
  ECG_Rhythm_M3	              		TEXT,
  ECG_Rhythm_Other_M3	          	TEXT,
  Stress_ECG_M3		              	TEXT,
  Stress_ECG_Date_M3	          	DATE,
  Stress_ECG_Detail_M3	        	TEXT,
  
  Lab_Date_M3		                	DATE,
  WBC_M3                         TEXT,
  TC_M3                          TEXT,
  Hb_M3                          TEXT,
  TG_M3                          TEXT,
  HDL_M3                         TEXT,
  Platelet_M3                    TEXT,
  LDL_M3                         TEXT,
  BUN_M3                         TEXT,
  Cr_M3                          TEXT,
  FG_M3                          TEXT,
  MDRD_M3                        TEXT,
  HbA1C_M3                       TEXT,
  AST_M3                         TEXT,
  hs_CRP_M3                      TEXT,
  ALT_M3                         TEXT,
  NT_Pro_BNP_M3                  TEXT,
  
  Aspirin_M3	                	 TEXT,
  Clopidogrel_M3	             	 TEXT,
  Prasugrel_M3	              	 TEXT,
  Ticagrelor_M3	             		 TEXT,
  Nicorandil_M3                  TEXT,
  Wafarin_M3                     TEXT,
  NOAC_M3                        TEXT,
  NOAC_name_M3                   TEXT,
  NOAC_dose_M3                   TEXT,
  BB_M3		                   		 TEXT,
  BB_name_M3                     TEXT,
  BB_dose_M3                     TEXT,
  DPP4_M3                        TEXT,
  DPP4_name_M3                   TEXT,
  DPP4_dose_M3                   TEXT,
  Metformin_M3                   TEXT,
  Metformin_dose_M3              TEXT,
  Sulf_M3                        TEXT,
  Sulf_name_M3                   TEXT,
  Sulf_dose_M3                   TEXT,
  Thia_M3                        TEXT,
  Thia_name_M3                   TEXT,
  Thia_dose_M3                   TEXT,
  GLP_M3                         TEXT,
  GLP_name_M3                    TEXT,
  GLP_dose_M3                    TEXT,
  Alpha_M3                       TEXT,
  Alpha_name_M3                  TEXT,
  Alpha_dose_M3                  TEXT,
  Statin_M3		                 	 TEXT,
  Statin_name_M3                 TEXT,
  Statin_dose_M3                 TEXT,
  ACE_M3	                   		 TEXT,
  ACE_name_M3                    TEXT,
  ACE_dose_M3                    TEXT,
  Nitrate_M3	                 	 TEXT,
  Calcium_M3	                 	 TEXT,
  Calcium_name_M3                TEXT,
  Calcium_dose_M3                TEXT,
  Trimetazidine_M3            	 TEXT,
  Insulin_M3                     TEXT,
  
  Event_Details_M3	             	TEXT,
  Death_date_M3		              	DATE,
  Death_reason_M3	              	TEXT,
  MI_date_M3		                	DATE,
  MI_Segment_M3		              	TEXT,
  MI_Type_M3		                	TEXT,
  MI_Stent_M3	                		TEXT,
  MI_Lesion_M3              			TEXT,
  MI_Vessel_M3	              		TEXT,
  MI_Treatment_M3	              	TEXT,
  MI_After_M3		                	TEXT,
  Rev_date_M3		                	DATE,
  Rev_Segment_M3	             		TEXT,
  Rev_Treatment_M3	             	TEXT,
  Rev_Lesion_M3	              		TEXT,
  Rev_Vessel_M3		              	TEXT,
  Rev_PCI_M3		                	TEXT,
  Stent_date_M3	              		DATE,
  Stent_Segment_M3            		TEXT,
  Stent_Type_M3		              	TEXT,
  Stent_arc_M3	              		TEXT,
  Clinical_feature_M3	          	TEXT,
  Clinical_feature_other_M3     	TEXT,
  CVA_date_M3		                	DATE,
  CVA_Type_M3	                		TEXT,
  
  Bleed_count_M3                 TEXT,
  Bleed1_date_M3                 DATE,
  BARC1_Type_M3                  TEXT,
  BARC1_ST_M3                    TEXT,
  BARC1_HT_M3                    TEXT,
  BARC1_Origin_M3                TEXT,
  BARC1_AT_M3                    TEXT,
  Bleed2_date_M3                 DATE,
  BARC2_Type_M3                  TEXT,
  BARC2_ST_M3                    TEXT,
  BARC2_HT_M3                    TEXT,
  BARC2_Origin_M3                TEXT,
  BARC2_AT_M3                    TEXT,
  
  Readmission_Date_M3             DATE,
  Readmission_Type_M3             TEXT,
  Readmission_Other_M3            TEXT,
  
  Imaging_M3	                		TEXT,
  Comment_M3	                		TEXT,
 
 -- M6 --
  FU_M6                           TEXT,
  Visit_Date_M6                   DATE,
  Visit_M6                        TEXT,
  Reason_M6                       TEXT,
  Other_M6                        TEXT,
  LastFU_M6                       DATE,
  SBP_M6                          TEXT,
  DBP_M6                          TEXT,
  HRT_M6                          TEXT,
  Event_M6                        TEXT,
  Cardiac_Status_M6		            TEXT,
  CCS_M6				                  TEXT,
  Other_Cardiac_Status_M6		      TEXT,
  -- Readmission_M6		            	TEXT,
  -- Readmission_Date_M6             DATE,
  -- Readmission_reason_M6       		TEXT,
  -- Readmission_reason_text_M6    	TEXT,
  ECG_Rhythm_M6	              		TEXT,
  ECG_Rhythm_Other_M6	          	TEXT,
  Stress_ECG_M6		              	TEXT,
  Stress_ECG_Date_M6	          	DATE,
  Stress_ECG_Detail_M6	        	TEXT,
  
  Lab_Date_M6		                	DATE,
  WBC_M6                         TEXT,
  TC_M6                          TEXT,
  Hb_M6                          TEXT,
  TG_M6                          TEXT,
  HDL_M6                         TEXT,
  Platelet_M6                    TEXT,
  LDL_M6                         TEXT,
  BUN_M6                         TEXT,
  Cr_M6                          TEXT,
  FG_M6                          TEXT,
  MDRD_M6                        TEXT,
  HbA1C_M6                       TEXT,
  AST_M6                         TEXT,
  hs_CRP_M6                      TEXT,
  ALT_M6                         TEXT,
  NT_Pro_BNP_M6                  TEXT,
  
  Aspirin_M6	                	 TEXT,
  Clopidogrel_M6	             	 TEXT,
  Prasugrel_M6	              	 TEXT,
  Ticagrelor_M6	             		 TEXT,
  Nicorandil_M6                  TEXT,
  Wafarin_M6                     TEXT,
  NOAC_M6                        TEXT,
  NOAC_name_M6                   TEXT,
  NOAC_dose_M6                   TEXT,
  BB_M6		                   		 TEXT,
  BB_name_M6                     TEXT,
  BB_dose_M6                     TEXT,
  DPP4_M6                        TEXT,
  DPP4_name_M6                   TEXT,
  DPP4_dose_M6                   TEXT,
  Metformin_M6                   TEXT,
  Metformin_dose_M6              TEXT,
  Sulf_M6                        TEXT,
  Sulf_name_M6                   TEXT,
  Sulf_dose_M6                   TEXT,
  Thia_M6                        TEXT,
  Thia_name_M6                   TEXT,
  Thia_dose_M6                   TEXT,
  GLP_M6                         TEXT,
  GLP_name_M6                    TEXT,
  GLP_dose_M6                    TEXT,
  Alpha_M6                       TEXT,
  Alpha_name_M6                  TEXT,
  Alpha_dose_M6                  TEXT,
  Statin_M6		                 	 TEXT,
  Statin_name_M6                 TEXT,
  Statin_dose_M6                 TEXT,
  ACE_M6	                   		 TEXT,
  ACE_name_M6                    TEXT,
  ACE_dose_M6                    TEXT,
  Nitrate_M6	                 	 TEXT,
  Calcium_M6	                 	 TEXT,
  Calcium_name_M6                TEXT,
  Calcium_dose_M6                TEXT,
  Trimetazidine_M6            	 TEXT,
  Insulin_M6                     TEXT,
  
  Event_Details_M6	             	TEXT,
  Death_date_M6		              	DATE,
  Death_reason_M6	              	TEXT,
  MI_date_M6		                	DATE,
  MI_Segment_M6		              	TEXT,
  MI_Type_M6		                	TEXT,
  MI_Stent_M6	                		TEXT,
  MI_Lesion_M6              			TEXT,
  MI_Vessel_M6	              		TEXT,
  MI_Treatment_M6	              	TEXT,
  MI_After_M6		                	TEXT,
  Rev_date_M6		                	DATE,
  Rev_Segment_M6	             		TEXT,
  Rev_Treatment_M6	             	TEXT,
  Rev_Lesion_M6	              		TEXT,
  Rev_Vessel_M6		              	TEXT,
  Rev_PCI_M6		                	TEXT,
  Stent_date_M6	              		DATE,
  Stent_Segment_M6            		TEXT,
  Stent_Type_M6		              	TEXT,
  Stent_arc_M6	              		TEXT,
  Clinical_feature_M6	          	TEXT,
  Clinical_feature_other_M6     	TEXT,
  CVA_date_M6		                	DATE,
  CVA_Type_M6	                		TEXT,
  
  Bleed_count_M6                 TEXT,
  Bleed1_date_M6                 DATE,
  BARC1_Type_M6                  TEXT,
  BARC1_ST_M6                    TEXT,
  BARC1_HT_M6                    TEXT,
  BARC1_Origin_M6                TEXT,
  BARC1_AT_M6                    TEXT,
  Bleed2_date_M6                 DATE,
  BARC2_Type_M6                  TEXT,
  BARC2_ST_M6                    TEXT,
  BARC2_HT_M6                    TEXT,
  BARC2_Origin_M6                TEXT,
  BARC2_AT_M6                    TEXT,
  
  Readmission_Date_M6             DATE,
  Readmission_Type_M6             TEXT,
  Readmission_Other_M6            TEXT,
  
  Imaging_M6	                		TEXT,
  Comment_M6	                		TEXT,

  -- Mf --
  FU_Mf                           TEXT,
  Visit_Date_Mf                   DATE,
  Visit_Mf                        TEXT,
  Reason_Mf                       TEXT,
  Other_Mf                        TEXT,
  LastFU_Mf                       DATE,
  SBP_Mf                          TEXT,
  DBP_Mf                          TEXT,
  HRT_Mf                          TEXT,
  Event_Mf                        TEXT,
  Cardiac_Status_Mf		            TEXT,
  CCS_Mf				                  TEXT,
  Other_Cardiac_Status_Mf		      TEXT,
  -- Readmission_Mf		            	TEXT,
  -- Readmission_Date_Mf             DATE,
  -- Readmission_reason_Mf       		TEXT,
  -- Readmission_reason_text_Mf    	TEXT,
  ECG_Rhythm_Mf	              		TEXT,
  ECG_Rhythm_Other_Mf	          	TEXT,
  Stress_ECG_Mf		              	TEXT,
  Stress_ECG_Date_Mf	          	DATE,
  Stress_ECG_Detail_Mf	        	TEXT,
  
  Lab_Date_Mf		                	DATE,
  WBC_Mf                         TEXT,
  TC_Mf                          TEXT,
  Hb_Mf                          TEXT,
  TG_Mf                          TEXT,
  HDL_Mf                         TEXT,
  Platelet_Mf                    TEXT,
  LDL_Mf                         TEXT,
  BUN_Mf                         TEXT,
  Cr_Mf                          TEXT,
  FG_Mf                          TEXT,
  MDRD_Mf                        TEXT,
  HbA1C_Mf                       TEXT,
  AST_Mf                         TEXT,
  hs_CRP_Mf                      TEXT,
  ALT_Mf                         TEXT,
  NT_Pro_BNP_Mf                  TEXT,
  
  Aspirin_Mf	                	 TEXT,
  Clopidogrel_Mf	             	 TEXT,
  Prasugrel_Mf	              	 TEXT,
  Ticagrelor_Mf	             		 TEXT,
  Nicorandil_Mf                  TEXT,
  Wafarin_Mf                     TEXT,
  NOAC_Mf                        TEXT,
  NOAC_name_Mf                   TEXT,
  NOAC_dose_Mf                   TEXT,
  BB_Mf		                   		 TEXT,
  BB_name_Mf                     TEXT,
  BB_dose_Mf                     TEXT,
  DPP4_Mf                        TEXT,
  DPP4_name_Mf                   TEXT,
  DPP4_dose_Mf                   TEXT,
  Metformin_Mf                   TEXT,
  Metformin_dose_Mf              TEXT,
  Sulf_Mf                        TEXT,
  Sulf_name_Mf                   TEXT,
  Sulf_dose_Mf                   TEXT,
  Thia_Mf                        TEXT,
  Thia_name_Mf                   TEXT,
  Thia_dose_Mf                   TEXT,
  GLP_Mf                         TEXT,
  GLP_name_Mf                    TEXT,
  GLP_dose_Mf                    TEXT,
  Alpha_Mf                       TEXT,
  Alpha_name_Mf                  TEXT,
  Alpha_dose_Mf                  TEXT,
  Statin_Mf		                 	 TEXT,
  Statin_name_Mf                 TEXT,
  Statin_dose_Mf                 TEXT,
  ACE_Mf	                   		 TEXT,
  ACE_name_Mf                    TEXT,
  ACE_dose_Mf                    TEXT,
  Nitrate_Mf	                 	 TEXT,
  Calcium_Mf	                 	 TEXT,
  Calcium_name_Mf                TEXT,
  Calcium_dose_Mf                TEXT,
  Trimetazidine_Mf            	 TEXT,
  Insulin_Mf                     TEXT,
  
  Event_Details_Mf	             	TEXT,
  Death_date_Mf		              	DATE,
  Death_reason_Mf	              	TEXT,
  MI_date_Mf		                	DATE,
  MI_Segment_Mf		              	TEXT,
  MI_Type_Mf		                	TEXT,
  MI_Stent_Mf	                		TEXT,
  MI_Lesion_Mf              			TEXT,
  MI_Vessel_Mf	              		TEXT,
  MI_Treatment_Mf	              	TEXT,
  MI_After_Mf		                	TEXT,
  Rev_date_Mf		                	DATE,
  Rev_Segment_Mf	             		TEXT,
  Rev_Treatment_Mf	             	TEXT,
  Rev_Lesion_Mf	              		TEXT,
  Rev_Vessel_Mf		              	TEXT,
  Rev_PCI_Mf		                	TEXT,
  Stent_date_Mf	              		DATE,
  Stent_Segment_Mf            		TEXT,
  Stent_Type_Mf		              	TEXT,
  Stent_arc_Mf	              		TEXT,
  Clinical_feature_Mf	          	TEXT,
  Clinical_feature_other_Mf     	TEXT,
  CVA_date_Mf		                	DATE,
  CVA_Type_Mf	                		TEXT,
  
  Bleed_count_Mf                 TEXT,
  Bleed1_date_Mf                 DATE,
  BARC1_Type_Mf                  TEXT,
  BARC1_ST_Mf                    TEXT,
  BARC1_HT_Mf                    TEXT,
  BARC1_Origin_Mf                TEXT,
  BARC1_AT_Mf                    TEXT,
  Bleed2_date_Mf                 DATE,
  BARC2_Type_Mf                  TEXT,
  BARC2_ST_Mf                    TEXT,
  BARC2_HT_Mf                    TEXT,
  BARC2_Origin_Mf                TEXT,
  BARC2_AT_Mf                    TEXT,
  
  Readmission_Date_Mf             DATE,
  Readmission_Type_Mf             TEXT,
  Readmission_Other_Mf            TEXT,
  
  Imaging_Mf	                		TEXT,
  Comment_Mf	                		TEXT,


  -- UNUSED --
  -- Withdrawal_M3                   TEXT,
  -- Withdrawal_Date_M3              DATE,
  -- Cause_M3                        TEXT,
  -- Comment_M3                      TEXT,

  -- Infomation --
  created_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by                      TEXT,
  modified_at                     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_by                     TEXT
)"

## same to "rct"
create_pros_query <- gsub(" rct ", " pros ", create_rct_query)

# dbExecute() executes a SQL statement with a connection object

# Drop the table if it already exists
dbExecute(conn, "DROP TABLE IF EXISTS rct")
dbExecute(conn, "DROP TABLE IF EXISTS pros")

# Execute the query created above
dbExecute(conn, create_rct_query)
dbExecute(conn, create_pros_query)

# example data

dat <- readRDS("data/eCRFexam.RDS")[, c(1:9, 11:12)][, -1]
names(dat)[1] <- "pid"
# dat[, 1] <- readRDS("data/random.RDS")[1, 1]
dat[, 1] <- "R-1"

dat <- cbind(

  # Demographics

  tibble(pid = dat[, 1]),
  Group = readRDS("data/random.RDS")[1, 2],
  tibble(
    Index_PCI_Date = as.character(as.Date(Sys.time()))
  ),
  dat[, -1],

  # Info
  tibble(
    created_at = as.character(lubridate::with_tz(Sys.time(), tzone = "UTC")),
    created_by = "jinseob2kim@gmail.com",
    modified_at = as.character(lubridate::with_tz(Sys.time(), tzone = "UTC")),
    modified_by = "jinseob2kim@gmail.com"
  )
)

dat$AMI_Type <- "NSTEMI"

rdat <- tibble(dat)
pdat <- tibble(dat)

# rdat[,1] <- paste0("R-", rdat[, 1])
pdat[, 1] <- paste0("P-", 1)

# Fill in the SQLite table with the values from the RDS file
DBI::dbWriteTable(
  conn,
  name = "rct",
  value = rdat,
  overwrite = FALSE,
  append = TRUE
)

DBI::dbWriteTable(
  conn,
  name = "pros",
  value = pdat,
  overwrite = FALSE,
  append = TRUE
)

# List tables to confirm 'mtcars' table exists
dbListTables(conn)

# disconnect from SQLite before continuing
dbDisconnect(conn)
