library(RSQLite)
library(tibble)
# setwd("~/zarathu/eCRF-SMCcath")
# Create a connection object with SQLite
conn <- dbConnect(
  RSQLite::SQLite(),
  "data/data.sqlite3"
)

# Create a query to prepare the 'mtcars' table with additional 'uid', 'id',
# & the 4 created/modified columns
create_rct_query <- "CREATE TABLE rct (
  -- Demographics --
  pid                             TEXT PRIMARY KEY,
  'Group'                         TEXT,
  DM                              TEXT,
  -- DM_Tx                           TEXT,
  Initial                         TEXT,
  Agree_Date                      DATE,
  Index_PCI_Date                  DATE,
  Birthday                        DATE,
  Age                             REAL,
  Sex                             TEXT,
  AMI_Type                        TEXT,
  Withdrawal                      TEXT,
  Withdrawal_date                 DATE,
  Withdrawal_reason               TEXT,
  Comment_demo                    TEXT,

  -- Admission --
  Date_adm                        DATE,
  Height                          REAL,
  Weight                          REAL,
  BMI                             REAL,
  BSA_adm                         REAL,
  SBP_adm                         REAL,
  DBP_adm                         REAL,
  HR_adm                          REAL,
  Diagnosis_adm                   TEXT,
  CCS_adm                         TEXT,
  BC_adm                          TEXT,
  Diagnosis_other_adm             TEXT,
  Diagnosis_comment_adm           TEXT,
  HTN                             TEXT,
  Diabetes_adm                    TEXT,
  Diabetes_detail_adm             TEXT,
  Hld_adm                         TEXT,
  Smoking                         TEXT,
  FHC_adm                         TEXT,
  CRF_adm                         TEXT,
  PCI_adm                         TEXT,
  PCABG_adm                       TEXT,
  PCVA_adm                        TEXT,
  PCHF_adm                        TEXT,
  Pvd_adm                         TEXT,
  PNTB_adm                        TEXT,
  TMT_adm                         TEXT,
  TMT_Date_adm                    DATE,
  TMT_detail_adm                  TEXT,
  MSPECT_adm                      TEXT,
  MSPECT_Date_adm                 DATE,
  MSPECT_detail_adm               TEXT,
  APET_adm                        TEXT,
  APET_Date_adm                   DATE,
  APET_detail_adm                 TEXT,
  CMR_adm                       TEXT,
  CMR_Date_adm                  DATE,
  CMR_detail_adm                TEXT,
  EEcho_adm                       TEXT,
  EEcho_Date_adm                  DATE,
  EEcho_detail_adm                TEXT,
  Corona_adm                      TEXT,
  Corona_date_adm                 DATE,
  Corona_BB_adm                   TEXT,
  Corona_Nitrate_adm              TEXT,
  EchoCG_adm                      TEXT,
  EchoCG_date_adm                 DATE,
  EchoCG_LVEF_adm                 TEXT,
  EchoCG_LVWMA_adm                TEXT,
  ECG_Rhythm_adm                  TEXT,
  ECG_Rhythm_others_adm           TEXT,
  Lab_Date_adm                    DATE,
  WBC_adm                         REAL,
  TC_adm                          REAL,
  Hb_adm                          REAL,
  TG_adm                          REAL,
  HDL_adm                         REAL,
  Platelet_adm                    REAL,
  LDL_adm                         REAL,
  BUN_adm                         REAL,
  Cr_adm                          REAL,
  FG_adm                          REAL,
  MDRD_adm                        REAL,
  HbA1C_adm                       REAL,
  AST_adm                         REAL,
  hs_CRP_adm                      REAL,
  ALT_adm                         REAL,
  NT_Pro_BNP_adm                  REAL,
  hCG_adm                         TEXT,
  BCK_adm                         REAL,
  PCK_adm                         REAL,
  BCKMB_adm                       REAL,
  PCKMB_adm                       REAL,
  BTroT_adm                       REAL,
  PTroT_adm                       REAL,
  -- Lab_comment_adm                 TEXT,
  Aspirin_adm	                		TEXT,
  Clopidogrel_adm	             		TEXT,
  Prasugrel_adm	              		TEXT,
  Ticagrelor_adm	             		TEXT,
  BB_adm		                   		TEXT,
  DPP4_adm                        TEXT,
  DPP4_name_adm                   TEXT,
  DPP4_dose_adm                   TEXT,
  Metformin_adm                   TEXT,
  Metformin_dose_adm              TEXT,
  Sulf_adm                        TEXT,
  Sulf_name_adm                   TEXT,
  Sulf_dose_adm                   TEXT,
  Thia_adm                        TEXT,
  Thia_name_adm                   TEXT,
  Thia_dose_adm                   TEXT,
  GLP_adm                         TEXT,
  GLP_name_adm                    TEXT,
  GLP_dose_adm                    TEXT,
  Alpha_adm                       TEXT,
  Alpha_name_adm                  TEXT,
  Alpha_dose_adm                  TEXT,
  Statin_adm		                 	TEXT,
  Statin_name_adm                 TEXT,
  Statin_dose_adm                 TEXT,
  ACE_adm	                   			TEXT,
  ACE_name_adm                    TEXT,
  ACE_dose_adm                    TEXT,
  Nitrate_adm	                 		TEXT,
  Calcium_adm	                 		TEXT,
  Calcium_name_adm                TEXT,
  Calcium_dose_adm                TEXT,
  Trimetazidine_adm            		TEXT,
  Insulin_adm                     TEXT,  

  -- Angiographics
  Date_ang                        DATE,
  Aspirin_ang                     TEXT,
  Aspirin_loading_ang             TEXT,
  Aspirin_detail_ang              TEXT,
  Clopidogrel_ang                 TEXT,
  Clopidogrel_loading_ang         TEXT,
  Clopidogrel_detail_ang          TEXT,
  Prasugrel_ang                   TEXT,
  Prasugrel_loading_ang           TEXT,
  Prasugrel_detail_ang            TEXT,
  Ticagrelor_ang                  TEXT,
  Ticagrelor_loading_ang          TEXT,
  Ticagrelor_detail_ang           TEXT,
  Procedure_type_ang              TEXT,
  Procedure_dose_ang              TEXT,
  Disease_extent_ang              TEXT,
  Left_main_ang                   TEXT,
  start_hour_ang                  REAL,
  start_min_ang                   REAL,
  end_hour_ang                    REAL,
  end_min_ang                     REAL,
  time_ang                        REAL,
  Catheter_diagnostic_ang         TEXT,
  Catheter_guiding_ang            TEXT,
  staged_PCI_ang                  TEXT,
  stagedPCI_count_ang             REAL,
  Gp_ang                          TEXT,
  Gp_detail_ang                   TEXT,
  Cul_cnt_ang                     REAL,
  Non_Cul_cnt_ang                 REAL,
  stagedPCI_1_ang                 DATE,
  stagedPCI_2_ang                 DATE,
  stagedPCI_1_procedure_ang       TEXT,
  stagedPCI_2_procedure_ang       TEXT,
  stagedPCI_1_procedure_dose_ang  TEXT,
  stagedPCI_2_procedure_dose_ang  TEXT,
  start_hour_PCI_1_ang            REAL,
  start_hour_PCI_2_ang            REAL,
  start_min_PCI_1_ang             REAL,
  start_min_PCI_2_ang             REAL,
  end_hour_PCI_1_ang              REAL,
  end_hour_PCI_2_ang              REAL,
  end_min_PCI_1_ang               REAL,
  end_min_PCI_2_ang               REAL,
  time_PCI_1_ang                  REAL,
  time_PCI_2_ang                  REAL,
  Diagnostic_PCI_1_ang            TEXT,
  Diagnostic_PCI_2_ang            TEXT,
  Guiding_PCI_1_ang               TEXT,
  Guiding_PCI_2_ang               TEXT,


  -- Outcomes

  Discharge_out                   DATE,
  General_out                     TEXT,
  General_detail_out              TEXT,
  General_detail_others_out       TEXT,
  Aspirin_out	                		TEXT,
  Clopidogrel_out	             		TEXT,
  Prasugrel_out	              		TEXT,
  Ticagrelor_out	             		TEXT,
  BB_out		                   		TEXT,
  WN_out		                  		TEXT,
  Statin_out		                 	TEXT,
  ACE_out	                   			TEXT,
  Nitrate_out	                 		TEXT,
  Calcium_out	                 		TEXT,
  Trimetazidine_out            		TEXT,
  Events_out                      TEXT,
  Events_detail_out               TEXT,
  Death_date_out                  DATE,
  Death_cause_out                 TEXT,
  MI_date_out                     DATE,
  MI_Segment_out                  TEXT,
  MI_Type_out                     TEXT,
  MI_Pre_out                      TEXT,
  MI_ST_out                       TEXT,
  MI_TL_out                       TEXT,
  MI_TV_out                       TEXT,
  MI_Treat_out                    TEXT,
  MI_After_out                    TEXT,
  RV_date_out                     DATE,
  RV_Segment_out                  TEXT,
  RV_CD_out                       TEXT,
  RV_ID_out                       TEXT,
  RV_Treat_out                    TEXT,
  RV_TL_out                       TEXT,
  RV_TV_out                       TEXT,
  RV_AVP_out                      TEXT,
  ST_date_out                     DATE,
  ST_Segment_out                  TEXT,
  ST_Type_out                     TEXT,
  ST_ARC_out                      TEXT,
  ST_Clinical_out                 TEXT,
  ST_Clinical_other_out           TEXT,
  CVA_date_out                    DATE,
  CVA_Type_out                    TEXT,
  CVA_VIS_out                     TEXT,
  Comment_out                     TEXT,


  -- Event --
  -- Last_FU_Date                    DATE,
  -- Death                           TEXT,
  -- Death_Date                      DATE,
  -- MI                              TEXT,
  -- MI_Date                         DATE,
  -- TVMI                            TEXT,
  -- TVMI_Date                       DATE,
  -- TLR                             TEXT,
  -- TLR_Date                        DATE,
  -- TVR                             TEXT,
  -- TVR_Date                        DATE,
  -- Readmission_Total               TEXT,
  -- Readmission_Total_Date          DATE,
  -- TLF                             TEXT,
  -- TLF_Date                        DATE,

  -- Lab --
  -- Lab_Date                        DATE,
  -- WBC                             REAL,
  -- Hb                              REAL,
  -- Plt                             REAL,
  -- Cholesterol                     REAL,
  -- TG                              REAL,
  -- LDL                             REAL,
  -- HDL                             REAL,
  -- BUN                             REAL,
  -- Creatinine                      REAL,
  -- eCFR                            REAL,
  -- Bilirubin                       REAL,
  -- AST                             REAL,
  -- ALT                             REAL,
  -- hsCRP                           REAL,
  -- HbA1c                           REAL,
  -- Pre_CK_MB                       REAL,
  -- Pre_cTnT                        REAL,
  -- Post_Peak_CK_MB                 REAL,
  -- Post_Peak_cTnT                  REAL,
  -- NT_proBNP_Baseline              REAL,
  -- Lactic_Acid_Pre                 REAL,
  -- Lactic_Acid_Peak                REAL,

  -- M1 --
  FU_M1                           TEXT,
  Visit_Date_M1                   DATE,
  Visit_M1                        TEXT,
  Reason_M1                       TEXT,
  Other_M1                        TEXT,
  LastFU_M1                       DATE,
  SBP_M1                          REAL,
  DBP_M1                          REAL,
  HRT_M1                          REAL,
  Event_M1                        TEXT,
  Cardiac_Status_M1		            TEXT,
  CCS_M1				                  TEXT,
  Other_Cardiac_Status_M1		      TEXT,
  Readmission_M1		            	TEXT,
  Readmission_Date_M1             DATE,
  Readmission_reason_M1       		TEXT,
  Readmission_reason_text_M1    	TEXT,
  ECG_Rhythm_M1	              		TEXT,
  ECG_Rhythm_Other_M1	          	TEXT,
  Stress_ECG_M1		              	TEXT,
  Stress_ECG_Date_M1	          	DATE,
  Stress_ECG_Detail_M1	        	TEXT,
  Lab_data_Unknown_M1	          	TEXT,
  Lab_Data_M1		                	DATE,
  WBC_M1	                  			REAL,
  TC_M1	                    			REAL,
  Hb_M1	                    			REAL,
  TG_M1	                    			REAL,
  Platelet_M1		                	REAL,
  HDL_M1		                  		REAL,
  BUN_M1                  				REAL,
  LDL_M1	                  			REAL,
  Cr_M1		                    		REAL,
  LDL_Cal_M1	                		REAL,
  BNP_M1	                  			REAL,
  FG_M1		                    		REAL,
  Pro_BNP_M1                			REAL,
  HbA1C_M1	                  		REAL,
  N_Pro_BNP_M1              			REAL,
  hs_CRP_M1	                  		REAL,
  CK_MB_M1	                  		REAL,
  Troponin_I_M1             			REAL,
  Troponin_T_M1	              		REAL,
  Aspirin_M1	                		TEXT,
  Clopidogrel_M1	             		TEXT,
  Prasugrel_M1	              		TEXT,
  Ticagrelor_M1	              		TEXT,
  BB_M1		                     		TEXT,
  WN_M1		                     		TEXT,
  Statin_M1		                   	TEXT,
  ACE_M1	                   			TEXT,
  Nitrate_M1	                 		TEXT,
  Calcium_M1	                 		TEXT,
  Trimetazidine_M1            		TEXT,
  Event_Details_M1	             	TEXT,
  Death_date_M1		              	DATE,
  Death_reason_M1	              	TEXT,
  MI_date_M1		                	DATE,
  MI_Segment_M1		              	REAL,
  MI_Type_M1		                	TEXT,
  MI_Stent_M1	                		TEXT,
  MI_Lesion_M1              			TEXT,
  MI_Vessel_M1	              		TEXT,
  MI_Treatment_M1	              	TEXT,
  MI_After_M1		                	TEXT,
  Rev_date_M1		                	DATE,
  Rev_Segment_M1	             		REAL,
  Rev_Treatment_M1	             	TEXT,
  Rev_Lesion_M1	              		TEXT,
  Rev_Vessel_M1		              	TEXT,
  Rev_PCI_M1		                	TEXT,
  Stent_date_M1	              		DATE,
  Stent_Segment_M1            		TEXT,
  Stent_Type_M1		              	TEXT,
  Stent_arc_M1	              		TEXT,
  Clinical_feature_M1	          	TEXT,
  Clinical_feature_other_M1     	TEXT,
  CVA_date_M1		                	DATE,
  CVA_Type_M1	                		TEXT,
  Imaging_M1	                		TEXT,
  Comment_M1	                		TEXT,

  -- M3 --
  FU_M3                           TEXT,
  Visit_Date_M3                   DATE,
  Visit_M3                        TEXT,
  Reason_M3                       TEXT,
  Other_M3                        TEXT,
  LastFU_M3                       DATE,
  SBP_M3                          REAL,
  DBP_M3                          REAL,
  HRT_M3                          REAL,
  Event_M3                        TEXT,
  Cardiac_Status_M3		            TEXT,
  CCS_M3				                  TEXT,
  Other_Cardiac_Status_M3		      TEXT,
  Readmission_M3		            	TEXT,
  Readmission_Date_M3             DATE,
  Readmission_reason_M3       		TEXT,
  Readmission_reason_text_M3    	TEXT,
  ECG_Rhythm_M3	              		TEXT,
  ECG_Rhythm_Other_M3	          	TEXT,
  Stress_ECG_M3		              	TEXT,
  Stress_ECG_Date_M3	          	DATE,
  Stress_ECG_Detail_M3	        	TEXT,
  Lab_data_Unknown_M3	          	TEXT,
  Lab_Data_M3		                	DATE,
  WBC_M3	                  			REAL,
  TC_M3	                    			REAL,
  Hb_M3	                    			REAL,
  TG_M3	                    			REAL,
  Platelet_M3		                	REAL,
  HDL_M3		                  		REAL,
  BUN_M3                  				REAL,
  LDL_M3	                  			REAL,
  Cr_M3		                    		REAL,
  LDL_Cal_M3	                		REAL,
  BNP_M3	                  			REAL,
  FG_M3		                    		REAL,
  Pro_BNP_M3                			REAL,
  HbA1C_M3	                  		REAL,
  N_Pro_BNP_M3              			REAL,
  hs_CRP_M3	                  		REAL,
  CK_MB_M3	                  		REAL,
  Troponin_I_M3             			REAL,
  Troponin_T_M3	              		REAL,
  Aspirin_M3	                		TEXT,
  Clopidogrel_M3	             		TEXT,
  Prasugrel_M3	              		TEXT,
  Ticagrelor_M3	              		TEXT,
  BB_M3		                     		TEXT,
  WN_M3		                     		TEXT,
  Statin_M3		                   	TEXT,
  ACE_M3	                   			TEXT,
  Nitrate_M3	                 		TEXT,
  Calcium_M3	                 		TEXT,
  Trimetazidine_M3            		TEXT,
  Event_Details_M3	             	TEXT,
  Death_date_M3		              	DATE,
  Death_reason_M3	              	TEXT,
  MI_date_M3		                	DATE,
  MI_Segment_M3		              	REAL,
  MI_Type_M3		                	TEXT,
  MI_Stent_M3	                		TEXT,
  MI_Lesion_M3              			TEXT,
  MI_Vessel_M3	              		TEXT,
  MI_Treatment_M3	              	TEXT,
  MI_After_M3		                	TEXT,
  Rev_date_M3		                	DATE,
  Rev_Segment_M3	             		REAL,
  Rev_Treatment_M3	             	TEXT,
  Rev_Lesion_M3	              		TEXT,
  Rev_Vessel_M3		              	TEXT,
  Rev_PCI_M3		                	TEXT,
  Stent_date_M3	              		DATE,
  Stent_Segment_M3            		TEXT,
  Stent_Type_M3		              	TEXT,
  Stent_arc_M3	              		TEXT,
  Clinical_feature_M3	          	TEXT,
  Clinical_feature_other_M3     	TEXT,
  CVA_date_M3		                	DATE,
  CVA_Type_M3	                		TEXT,
  Imaging_M3	                		TEXT,
  Comment_M3	                		TEXT,

  -- M6 --
  FU_M6                           TEXT,
  Visit_Date_M6                   DATE,
  Visit_M6                        TEXT,
  Reason_M6                       TEXT,
  Other_M6                        TEXT,
  LastFU_M6                       DATE,
  SBP_M6                          REAL,
  DBP_M6                          REAL,
  HRT_M6                          REAL,
  Event_M6                        TEXT,
  Cardiac_Status_M6		            TEXT,
  CCS_M6				                  TEXT,
  Other_Cardiac_Status_M6		      TEXT,
  Readmission_M6		            	TEXT,
  Readmission_Date_M6             DATE,
  Readmission_reason_M6       		TEXT,
  Readmission_reason_text_M6    	TEXT,
  ECG_Rhythm_M6	              		TEXT,
  ECG_Rhythm_Other_M6	          	TEXT,
  Stress_ECG_M6		              	TEXT,
  Stress_ECG_Date_M6	          	DATE,
  Stress_ECG_Detail_M6	        	TEXT,
  Lab_data_Unknown_M6	          	TEXT,
  Lab_Data_M6		                	DATE,
  WBC_M6	                  			REAL,
  TC_M6	                    			REAL,
  Hb_M6	                    			REAL,
  TG_M6	                    			REAL,
  Platelet_M6		                	REAL,
  HDL_M6		                  		REAL,
  BUN_M6                  				REAL,
  LDL_M6	                  			REAL,
  Cr_M6		                    		REAL,
  LDL_Cal_M6	                		REAL,
  BNP_M6	                  			REAL,
  FG_M6		                    		REAL,
  Pro_BNP_M6                			REAL,
  HbA1C_M6	                  		REAL,
  N_Pro_BNP_M6              			REAL,
  hs_CRP_M6	                  		REAL,
  CK_MB_M6	                  		REAL,
  Troponin_I_M6             			REAL,
  Troponin_T_M6	              		REAL,
  Aspirin_M6	                		TEXT,
  Clopidogrel_M6	             		TEXT,
  Prasugrel_M6	              		TEXT,
  Ticagrelor_M6	              		TEXT,
  BB_M6		                     		TEXT,
  WN_M6		                     		TEXT,
  Statin_M6		                   	TEXT,
  ACE_M6	                   			TEXT,
  Nitrate_M6	                 		TEXT,
  Calcium_M6	                 		TEXT,
  Trimetazidine_M6            		TEXT,
  Event_Details_M6	             	TEXT,
  Death_date_M6		              	DATE,
  Death_reason_M6	              	TEXT,
  MI_date_M6		                	DATE,
  MI_Segment_M6		              	REAL,
  MI_Type_M6		                	TEXT,
  MI_Stent_M6	                		TEXT,
  MI_Lesion_M6              			TEXT,
  MI_Vessel_M6	              		TEXT,
  MI_Treatment_M6	              	TEXT,
  MI_After_M6		                	TEXT,
  Rev_date_M6		                	DATE,
  Rev_Segment_M6	             		REAL,
  Rev_Treatment_M6	             	TEXT,
  Rev_Lesion_M6	              		TEXT,
  Rev_Vessel_M6		              	TEXT,
  Rev_PCI_M6		                	TEXT,
  Stent_date_M6	              		DATE,
  Stent_Segment_M6            		TEXT,
  Stent_Type_M6		              	TEXT,
  Stent_arc_M6	              		TEXT,
  Clinical_feature_M6	          	TEXT,
  Clinical_feature_other_M6     	TEXT,
  CVA_date_M6		                	DATE,
  CVA_Type_M6	                		TEXT,
  Imaging_M6	                		TEXT,
  Comment_M6	                		TEXT,

  -- Mf --
  FU_Mf                           TEXT,
  Visit_Date_Mf                   DATE,
  Visit_Mf                        TEXT,
  Reason_Mf                       TEXT,
  Other_Mf                        TEXT,
  LastFU_Mf                       DATE,
  SBP_Mf                          REAL,
  DBP_Mf                          REAL,
  HRT_Mf                          REAL,
  Event_Mf                        TEXT,
  Cardiac_Status_Mf		            TEXT,
  CCS_Mf				                  TEXT,
  Other_Cardiac_Status_Mf		      TEXT,
  Readmission_Mf		            	TEXT,
  Readmission_Date_Mf             DATE,
  Readmission_reason_Mf       		TEXT,
  Readmission_reason_text_Mf    	TEXT,
  ECG_Rhythm_Mf	              		TEXT,
  ECG_Rhythm_Other_Mf	          	TEXT,
  Stress_ECG_Mf		              	TEXT,
  Stress_ECG_Date_Mf	          	DATE,
  Stress_ECG_Detail_Mf	        	TEXT,
  Lab_data_Unknown_Mf	          	TEXT,
  Lab_Data_Mf		                	DATE,
  WBC_Mf	                  			REAL,
  TC_Mf	                    			REAL,
  Hb_Mf	                    			REAL,
  TG_Mf	                    			REAL,
  Platelet_Mf		                	REAL,
  HDL_Mf		                  		REAL,
  BUN_Mf                  				REAL,
  LDL_Mf	                  			REAL,
  Cr_Mf		                    		REAL,
  LDL_Cal_Mf	                		REAL,
  BNP_Mf	                  			REAL,
  FG_Mf		                    		REAL,
  Pro_BNP_Mf                			REAL,
  HbA1C_Mf	                  		REAL,
  N_Pro_BNP_Mf              			REAL,
  hs_CRP_Mf	                  		REAL,
  CK_MB_Mf	                  		REAL,
  Troponin_I_Mf             			REAL,
  Troponin_T_Mf	              		REAL,
  Aspirin_Mf	                		TEXT,
  Clopidogrel_Mf	             		TEXT,
  Prasugrel_Mf	              		TEXT,
  Ticagrelor_Mf	              		TEXT,
  BB_Mf		                     		TEXT,
  WN_Mf		                     		TEXT,
  Statin_Mf		                   	TEXT,
  ACE_Mf	                   			TEXT,
  Nitrate_Mf	                 		TEXT,
  Calcium_Mf	                 		TEXT,
  Trimetazidine_Mf            		TEXT,
  Event_Details_Mf	             	TEXT,
  Death_date_Mf		              	DATE,
  Death_reason_Mf	              	TEXT,
  MI_date_Mf		                	DATE,
  MI_Segment_Mf		              	REAL,
  MI_Type_Mf		                	TEXT,
  MI_Stent_Mf	                		TEXT,
  MI_Lesion_Mf              			TEXT,
  MI_Vessel_Mf	              		TEXT,
  MI_Treatment_Mf	              	TEXT,
  MI_After_Mf		                	TEXT,
  Rev_date_Mf		                	DATE,
  Rev_Segment_Mf	             		REAL,
  Rev_Treatment_Mf	             	TEXT,
  Rev_Lesion_Mf	              		TEXT,
  Rev_Vessel_Mf		              	TEXT,
  Rev_PCI_Mf		                	TEXT,
  Stent_date_Mf	              		DATE,
  Stent_Segment_Mf            		TEXT,
  Stent_Type_Mf		              	TEXT,
  Stent_arc_Mf	              		TEXT,
  Clinical_feature_Mf	          	TEXT,
  Clinical_feature_other_Mf     	TEXT,
  CVA_date_Mf		                	DATE,
  CVA_Type_Mf	                		TEXT,
  Imaging_Mf	                		TEXT,
  Comment_Mf	                		TEXT,


  -- UNUSED --
  -- Withdrawal_M3                   TEXT,
  -- Withdrawal_Date_M3              DATE,
  -- Cause_M3                        TEXT,
  -- Comment_M3                      TEXT,

  -- Infomation --
  created_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by                      TEXT,
  modified_at                     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_by                     TEXT
)"

## same to "rct"
create_pros_query <- gsub(" rct ", " pros ", create_rct_query)

# dbExecute() executes a SQL statement with a connection object

# Drop the table if it already exists
dbExecute(conn, "DROP TABLE IF EXISTS rct")
dbExecute(conn, "DROP TABLE IF EXISTS pros")

# Execute the query created above
dbExecute(conn, create_rct_query)
dbExecute(conn, create_pros_query)

# example data

dat <- readRDS("data/eCRFexam.RDS")[, c(1:9, 11:12)][, -1]
names(dat)[1] <- "pid"
# dat[, 1] <- readRDS("data/random.RDS")[1, 1]
dat[, 1] <- "R-1"

dat <- cbind(

  # Demographics

  tibble(pid = dat[, 1]),
  Group = readRDS("data/random.RDS")[1, 2],
  tibble(
    Index_PCI_Date = as.character(as.Date(Sys.time()))
  ),
  dat[, -1],

  # Admission

  tibble(
    SBP_adm = 120
  ),

  # Outcomes

  tibble(
    Discharge_out = as.character(as.Date(Sys.time())),
    Comment_out = "Comment outcomes"
  ),

  # Event
  #
  # tibble(
  #  Last_FU_Date = as.character(as.Date(Sys.time())),
  #  Death = "1",
  #  Death_Date = as.character(as.Date(Sys.time())),
  #  MI = "1",
  #  MI_Date = as.character(as.Date(Sys.time())),
  #  TVMI = "1",
  #  TVMI_Date = as.character(as.Date(Sys.time())),
  #  TLR = "1",
  #  TLR_Date = as.character(as.Date(Sys.time())),
  #  TVR = "1",
  #  TVR_Date = as.character(as.Date(Sys.time())),
  #  Readmission_Total = "1",
  #  Readmission_Total_Date = as.character(as.Date(Sys.time())),
  #  TLF = "1",
  #  TLF_Date = as.character(as.Date(Sys.time()))
  # ),

  # Lab
  # tibble(
  #  Lab_Date = as.character(as.Date(Sys.time())),
  #  WBC = 7.5,
  #  Hb = 13,
  #  Plt = 215,
  #  Cholesterol = 230,
  #  TG = 150,
  #  LDL = 138,
  #  HDL = 32,
  #  BUN = 24.8,
  #  Creatinine = 0.79,
  #  eCFR = 97.78,
  #  Bilirubin = 1.1,
  #  AST = 34,
  #  ALT = 32,
  #  hsCRP = 0.03,
  #  HbA1c = 5,
  #  Pre_CK_MB = 1.67,
  #  Pre_cTnT = 0.058,
  #  Post_Peak_CK_MB = 198.78,
  #  Post_Peak_cTnT = 1.875,
  #  NT_proBNP_Baseline = 148.7,
  #  Lactic_Acid_Pre = 2.1,
  #  Lactic_Acid_Peak = 3
  # ),

  # M1
  tibble(
    FU_M1 = "0",
    Visit_Date_M1 = as.character(as.Date(Sys.time() + lubridate::days(90))),
    Visit_M1 = "0",
    SBP_M1 = 121,
    DBP_M1 = 81,
    HRT_M1 = 61,
    Event_M1 = "1",
    Comment_M1 = "This is Comment M1"
  ),


  # M3
  tibble(
    FU_M3 = "0",
    Visit_Date_M3 = as.character(as.Date(Sys.time() + lubridate::days(90))),
    Visit_M3 = "0",
    SBP_M3 = 120,
    DBP_M3 = 80,
    HRT_M3 = 60,
    Event_M3 = "1",
    Comment_M3 = "This is Comment Month 3"
  ),

  # M6
  tibble(
    FU_M6 = "0",
    Visit_Date_M6 = as.character(as.Date(Sys.time() + lubridate::days(90))),
    Visit_M6 = "0",
    SBP_M6 = 126,
    DBP_M6 = 86,
    HRT_M6 = 66,
    Event_M6 = "1",
    Comment_M6 = "This is Comment M6"
  ),

  # Mf
  tibble(
    FU_Mf = "0",
    Visit_Date_Mf = as.character(as.Date(Sys.time() + lubridate::days(90))),
    Visit_Mf = "0",
    SBP_Mf = 124,
    DBP_Mf = 84,
    HRT_Mf = 64,
    Event_Mf = "1",
    Comment_Mf = "This is Comment Mfinal"
  ),

  # Info
  tibble(
    created_at = as.character(lubridate::with_tz(Sys.time(), tzone = "UTC")),
    created_by = "jinseob2kim@gmail.com",
    modified_at = as.character(lubridate::with_tz(Sys.time(), tzone = "UTC")),
    modified_by = "jinseob2kim@gmail.com"
  )
)


# for (i in c(1, 10:24)) {
#  class(dat[, i]) <- "character"
# }

dat$AMI_Type <- "NSTEMI"

rdat <- tibble(dat)
pdat <- tibble(dat)

# rdat[,1] <- paste0("R-", rdat[, 1])
pdat[, 1] <- paste0("P-", 1)

# Fill in the SQLite table with the values from the RDS file
DBI::dbWriteTable(
  conn,
  name = "rct",
  value = rdat,
  overwrite = FALSE,
  append = TRUE
)

DBI::dbWriteTable(
  conn,
  name = "pros",
  value = pdat,
  overwrite = FALSE,
  append = TRUE
)

# List tables to confirm 'mtcars' table exists
dbListTables(conn)

# disconnect from SQLite before continuing
dbDisconnect(conn)
